name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - id: nvmrc
      uses: browniebroke/read-nvmrc-action@v1
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '${{ steps.nvmrc.outputs.node_version }}'
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
    - run: pnpm test
